DROP DATABASE IF EXISTS `Bot`;
CREATE DATABASE `Bot` DEFAULT CHARACTER SET utf8;
USE `Bot`;

CREATE TABLE `Admins` (
  `id` BIGINT,
  `first_name` TEXT DEFAULT NULL,
  `last_name` TEXT DEFAULT NULL,
  `username` VARCHAR(32) UNIQUE DEFAULT NULL,
  `phone_number` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8;

CREATE TABLE `Blacklist` (
  `id` BIGINT,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8;

CREATE TABLE `Data` (
  `id` BIGINT,
  `staff_group` BIGINT,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8;

CREATE TABLE `Languages` (
  `lang_code` VARCHARACTER(20),
  `start_message` TEXT DEFAULT NULL,
  `help_message` TEXT DEFAULT NULL,
  PRIMARY KEY (`lang_code`)
) DEFAULT CHARACTER SET utf8;
